cam: 
	g++ -o CamTex CamTex.cpp -lGL -lglut -I/usr/include/opencv2 -I/usr/include/GL `pkg-config opencv --cflags --libs`
test: 
	g++ -o test test.cpp -lglut -lassimp -lglfw -I/usr/include/glm -I../../vendor/glad/include/glad
